version: "3.6"
services:
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  postgres:
    image: postgres:16.1
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=webprice
      - POSTGRES_USER=webprice
      - POSTGRES_DB=webprice

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8083:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret